import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Boxes, Check, ChevronRight, CircleAlert, Cloud, ExternalLink, FileText, GitBranch, Layers3, Menu, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import { glossary, learningCards, paths, resources, type ContentType, type Level } from './content'
import { Glossary as GlossaryPage } from './pages/Glossary'
import { Resources as ResourcesPage } from './pages/Resources'

type View = 'home' | 'enterprise-architecture' | 'azure-fundamentals' | 'landing-zones' | 'architecture-practice' | 'profuturo' | 'glossary' | 'resources'

const navItems: { id: View; label: string }[] = [
  { id: 'home', label: 'Inicio' },
  { id: 'enterprise-architecture', label: 'Fundamentos de EA' },
  { id: 'azure-fundamentals', label: 'Fundamentos de Azure' },
  { id: 'profuturo', label: 'Landing Zone Profuturo' },
]

function hashToView(): View {
  const value = window.location.hash.slice(1) as View
  return navItems.some((item) => item.id === value) || ['architecture-practice', 'glossary', 'resources'].includes(value) ? value : 'home'
}

export function App() {
  const [view, setView] = useState<View>(hashToView())
  const [menuOpen, setMenuOpen] = useState(false)
  const [search, setSearch] = useState('')

  useEffect(() => {
    const onHashChange = () => { setView(hashToView()); window.scrollTo({ top: 0, behavior: 'smooth' }) }
    window.addEventListener('hashchange', onHashChange)
    return () => window.removeEventListener('hashchange', onHashChange)
  }, [])

  const navigate = (next: View) => { window.location.hash = next; setMenuOpen(false) }
  const searchResults = useMemo(() => [...learningCards, ...paths.map((path) => ({ id: path.title, eyebrow: 'RUTA DE APRENDIZAJE', title: path.title, description: path.description, level: path.level as Level, type: 'Guía' as ContentType, accent: 'blue' }))].filter((item) => `${item.title} ${item.description}`.toLowerCase().includes(search.toLowerCase())), [search])

  return <div className="app-shell">
    <header className="site-header">
      <a className="brand" href="#home" onClick={() => setMenuOpen(false)}><img className="brand-logo" src={`${import.meta.env.BASE_URL}logo-profuturo.png`} alt="Profuturo" style={{ width: 32, height: 32, borderRadius: 8, objectFit: 'cover' }} /><span>Profuturo | <em>First Steps</em></span></a>
      <button className="menu-toggle" aria-label="Toggle navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      <nav className={menuOpen ? 'main-nav open' : 'main-nav'} aria-label="Navegación principal">{navItems.map((item) => <a key={item.id} className={view === item.id ? 'active' : ''} href={`#${item.id}`} onClick={() => setMenuOpen(false)}>{item.label}</a>)}<a href="#resources" onClick={() => setMenuOpen(false)}>Recursos <ExternalLink size={13} /></a></nav>
      <a className="header-action" href="#glossary">Abrir glosario <ArrowRight size={15} /></a>
    </header>
    <main>
      {view === 'home' && <Home navigate={navigate} search={search} setSearch={setSearch} results={searchResults} />}
      {view === 'enterprise-architecture' && <Article view="enterprise" navigate={navigate} />}
      {view === 'azure-fundamentals' && <Article view="azure" navigate={navigate} />}
      {view === 'landing-zones' && <Article view="landing" navigate={navigate} />}
      {view === 'architecture-practice' && <Article view="practice" navigate={navigate} />}
      {view === 'profuturo' && <Profuturo navigate={navigate} />}
      {view === 'glossary' && <GlossaryPage />}
      {view === 'resources' && <ResourcesPage />}
    </main>
    <footer><div className="footer-brand"><span className="brand-mark"><Sparkles size={15} /></span><strong>First Steps</strong><p>Una guía viva para comenzar el camino de arquitectura.</p></div><div><span className="footer-label">Referencias oficiales</span><a href="https://learn.microsoft.com/azure/architecture/" target="_blank" rel="noreferrer">Azure Architecture Center <ExternalLink size={12} /></a><a href="https://docs.github.com/pages" target="_blank" rel="noreferrer">GitHub Pages <ExternalLink size={12} /></a></div><div className="footer-note"><CircleAlert size={16} /><span>La información interna de Profuturo está marcada y debe validarse antes de utilizarse.</span></div></footer>
  </div>
}

function Home({ navigate, search, setSearch, results }: { navigate: (view: View) => void; search: string; setSearch: (value: string) => void; results: typeof learningCards }) {
  return <>
    <section className="hero"><div className="hero-copy"><div className="kicker"><span className="pulse-dot" /> ONBOARDING / ARQUITECTURA EMPRESARIAL</div><h1>Tus primeros pasos en <span>Arquitectura Empresarial.</span></h1><p className="hero-lede">Una guía viva para entender cómo se conectan negocio, tecnología y nube en Profuturo. Aprende el lenguaje, explora los patrones y construye contexto.</p><div className="hero-actions"><button className="button primary" onClick={() => navigate('enterprise-architecture')}>Comenzar aprendizaje <ArrowRight size={17} /></button><button className="button text-button" onClick={() => navigate('landing-zones')}>Explorar Azure Landing Zone <ChevronRight size={17} /></button></div><div className="hero-meta"><span><Check size={15} /> Conceptos verificados</span><span><Check size={15} /> Sin información confidencial</span></div></div><div className="hero-visual" aria-label="Diagrama conceptual de negocio, plataforma y workloads"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core"><Cloud size={27} /><strong>Azure</strong><small>base gobernada</small></div><div className="orbit-label label-top"><Layers3 size={16} /> Plataforma</div><div className="orbit-label label-right"><Boxes size={16} /> Workloads</div><div className="orbit-label label-bottom"><ShieldCheck size={16} /> Gobierno</div></div></section>
    <section className="search-band"><div><span className="section-eyebrow">BUSCA EN LA GUÍA</span><h2>¿Por dónde te gustaría comenzar?</h2></div><div className="search-wrap"><Search size={19} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Prueba “RBAC”, “Landing Zone” o “ADR”" aria-label="Buscar documentación" />{search && <button aria-label="Limpiar búsqueda" onClick={() => setSearch('')}><X size={16} /></button>}<div className="search-results">{search && results.slice(0, 5).map((result) => <a key={result.id} href={`#${result.id}`}><span>{result.title}</span><ArrowRight size={14} /></a>)}{search && !results.length && <span className="no-results">Aún no hay una guía relacionada.</span>}</div></div></section>
    <section className="section learning-section"><div className="section-heading"><div><span className="section-eyebrow">EL CURRÍCULO PRINCIPAL</span><h2>Rutas de aprendizaje</h2></div><button className="button text-button" onClick={() => navigate('glossary')}>Explorar glosario <ArrowRight size={16} /></button></div><div className="learning-grid">{learningCards.map((card) => <LearningCard key={card.id} card={card} navigate={navigate} />)}</div></section>
    <section className="section split-section"><div><span className="section-eyebrow">UN LENGUAJE COMÚN</span><h2>Conceptos que aclaran el mapa.</h2><p className="muted">La arquitectura se entiende mejor cuando las palabras tienen límites claros. Comienza con los fundamentos y conéctalos con la plataforma.</p><button className="button dark" onClick={() => navigate('azure-fundamentals')}>Explorar la jerarquía de Azure <ArrowRight size={16} /></button></div><div className="concept-list">{[['01', 'Capacidad de negocio', 'El resultado que la organización necesita.'], ['02', 'Decisión arquitectónica', 'Una elección deliberada con contexto y trade-offs.'], ['03', 'Base cloud', 'Un entorno gobernado donde los workloads pueden crecer.']].map(([number, title, copy]) => <div className="concept-item" key={number}><span>{number}</span><div><strong>{title}</strong><p>{copy}</p></div><ChevronRight size={18} /></div>)}</div></section>
    <section className="section latest-section"><div className="section-heading"><div><span className="section-eyebrow">SIGUE EXPLORANDO</span><h2>Puntos de partida recientes</h2></div><span className="status-chip"><span /> Contenido estático y mantenible</span></div><div className="latest-grid"><div className="latest-feature" onClick={() => navigate('profuturo')}><div className="feature-icon"><ShieldCheck /></div><span className="tag">ARQUITECTURA</span><h3>Landing Zone de Profuturo</h3><p>Un espacio preparado para documentar la implementación interna sin asumir datos que aún no han sido validados.</p><span className="read-link">Abrir el espacio de referencia <ArrowRight size={15} /></span></div><div className="latest-side"><div><FileText size={18} /><strong>Architecture Decision Records</strong><p>Una plantilla para hacer visibles las decisiones y sus trade-offs.</p></div><div><BookOpen size={18} /><strong>Cómo leer un diagrama cloud</strong><p>De los límites organizacionales a los componentes desplegables.</p></div></div></div></section>
  </>
}

function LearningCard({ card, navigate }: { card: typeof learningCards[number]; navigate: (view: View) => void }) { const destination = card.id as View; return <button className={`learning-card ${card.accent}`} onClick={() => navigate(destination)}><div className="card-top"><span className="card-eyebrow">{card.eyebrow}</span><span className={`level ${card.level.toLowerCase()}`}>{card.level}</span></div><div className="card-icon">{card.id === 'azure-fundamentals' ? <Cloud /> : card.id === 'landing-zones' ? <Layers3 /> : card.id === 'architecture-practice' ? <FileText /> : <Boxes />}</div><h3>{card.title}</h3><p>{card.description}</p><div className="card-bottom"><span>{card.type}</span><ArrowRight size={17} /></div></button> }

function Article({ view, navigate }: { view: 'enterprise' | 'azure' | 'landing' | 'practice'; navigate: (view: View) => void }) {
  const copy = { enterprise: { label: '01 / FUNDAMENTOS', title: 'Arquitectura Empresarial', intro: 'La arquitectura empresarial crea un lenguaje común para alinear estrategia, capacidades, procesos y tecnología.', icon: <Boxes />, next: 'azure-fundamentals' as View, nextLabel: 'Fundamentos de Azure' }, azure: { label: '02 / NUBE', title: 'Fundamentos de Azure', intro: 'Azure organiza recursos, identidades y políticas en una jerarquía que permite operar la nube con claridad.', icon: <Cloud />, next: 'landing-zones' as View, nextLabel: 'Azure Landing Zones' }, landing: { label: '03 / PLATAFORMA', title: 'Azure Landing Zones', intro: 'Una Landing Zone es una base gobernada y escalable para que los equipos entreguen workloads con consistencia.', icon: <Layers3 />, next: 'profuturo' as View, nextLabel: 'Landing Zone de Profuturo' }, practice: { label: '04 / PRÁCTICA', title: 'Arquitectura en la práctica', intro: 'El trabajo cotidiano de arquitectura convierte preguntas ambiguas en decisiones trazables y compartibles.', icon: <FileText />, next: 'glossary' as View, nextLabel: 'Glosario' } }[view]
  return <article className="article"><div className="article-header"><div className="article-icon">{copy.icon}</div><span className="section-eyebrow">{copy.label}</span><h1>{copy.title}</h1><p>{copy.intro}</p><div className="article-tags"><span className="tag">CONCEPT</span><span className="tag">GUIDE</span><span className="level beginner">Beginner</span></div></div><div className="article-layout"><aside className="toc"><span>ON THIS PAGE</span><a href="#why">Why it matters</a><a href="#model">A simple model</a><a href="#next">Keep going</a></aside><div className="article-body"><section id="why"><h2>Why it matters</h2><p>{view === 'enterprise' ? 'No se trata de dibujar diagramas por sí mismos. Se trata de hacer explícita la relación entre lo que el negocio necesita y las decisiones tecnológicas que lo hacen posible.' : view === 'azure' ? 'Antes de elegir un servicio, conviene entender los límites que Azure ofrece: tenant, management groups, subscriptions, resource groups y resources.' : view === 'landing' ? 'La landing zone reduce decisiones repetidas y establece capacidades de identidad, red, seguridad, gobierno, operaciones y costos para los workloads.' : 'Una buena práctica de arquitectura hace visibles los requerimientos no funcionales, las dependencias, los supuestos y los riesgos antes de que se conviertan en sorpresas.'}</p></section><section id="model"><h2>{view === 'azure' ? 'The Azure hierarchy' : view === 'landing' ? 'The foundation model' : 'A simple model'}</h2>{view === 'azure' ? <Hierarchy /> : view === 'landing' ? <FoundationDiagram /> : <div className="principles">{(view === 'enterprise' ? [['Business', 'Capabilities, outcomes and constraints'], ['Architecture', 'Principles, standards and decisions'], ['Technology', 'Applications, data and infrastructure']] : [['Understand', 'Requirements, context and constraints'], ['Decide', 'Options, trade-offs and an ADR'], ['Communicate', 'A diagram and a review others can use']]).map(([title, text]) => <div key={title}><span>{title}</span><strong>{text}</strong></div>)}</div>}</section><section id="next" className="callout"><CircleAlert size={19} /><div><strong>Keep the boundary clear</strong><p>Las explicaciones anteriores son conceptuales. Cualquier detalle de implementación interna requiere una fuente oficial y una revisión del equipo responsable.</p></div></section><button className="button primary" onClick={() => navigate(copy.next)}>{copy.nextLabel} <ArrowRight size={16} /></button></div></div></article>
}

function Hierarchy() { return <div className="hierarchy" aria-label="Jerarquía de Azure desde tenant hasta los recursos"><div><strong>Tenant</strong><span>Límite de identidad</span></div><ChevronRight /><div><strong>Management groups</strong><span>Ámbito de gobierno</span></div><ChevronRight /><div><strong>Subscriptions</strong><span>Límite de administración</span></div><ChevronRight /><div><strong>Resource groups</strong><span>Límite de ciclo de vida</span></div><ChevronRight /><div><strong>Resources</strong><span>Servicios desplegables</span></div></div> }
function FoundationDiagram() { return <div className="foundation-diagram" aria-label="Componentes de una base de Landing Zone"><div className="foundation-platform"><span>BASE DE PLATAFORMA</span><div><b>Identidad</b><b>Conectividad</b><b>Seguridad</b><b>Administración</b></div></div><div className="foundation-arrow">↓ habilita ↓</div><div className="workloads"><div><strong>Workload A</strong><span>Equipo de aplicaciones</span></div><div><strong>Workload B</strong><span>Equipo de producto</span></div><div><strong>Workload C</strong><span>Equipo de datos</span></div></div></div> }

function Profuturo({ navigate }: { navigate: (view: View) => void }) { const modules = ['Visión general', 'Arquitectura de alto nivel', 'Networking y conectividad', 'Identidad y accesos', 'Seguridad y cumplimiento', 'Gobierno y políticas', 'Servicios compartidos', 'Observabilidad', 'Automatización']; return <article className="article profuturo"><div className="article-header"><div className="article-icon orange"><ShieldCheck /></div><span className="section-eyebrow">ESPACIO DE REFERENCIA INTERNO</span><h1>Landing Zone de Profuturo</h1><p>Un índice preparado para documentar la implementación interna. Hoy contiene contexto general y espacios explícitos para validación.</p><div className="validation-banner"><CircleAlert size={18} /><span><strong>Pendiente de validación:</strong> no se documentan topología, nombres de recursos, subscriptions, políticas ni procesos internos sin confirmación.</span></div></div><div className="module-grid">{modules.map((module, index) => <div className="module-card" key={module}><span className="module-number">{String(index + 1).padStart(2, '0')}</span><h3>{module}</h3><p>Objetivo, conceptos, referencias y diagrama por documentar.</p><span className="pending"><CircleAlert size={13} /> Pendiente de validación</span></div>)}</div><div className="reference-panel"><h2>Límite conocido</h2><p>La arquitectura conceptual de Azure Landing Zones de Microsoft sirve como referencia. La correspondencia con el entorno de Profuturo debe ser revisada y aprobada internamente.</p><button className="button dark" onClick={() => navigate('resources')}>Abrir referencias oficiales <ExternalLink size={15} /></button></div></article> }

